#ifndef QTMEDIAPLAYER_GLOBAL_H
#define QTMEDIAPLAYER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QTMEDIAPLAYER_LIBRARY)
#  define QTMEDIAPLAYERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define QTMEDIAPLAYERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // QTMEDIAPLAYER_GLOBAL_H
